/* eslint-disable @stylistic/quote-props */
/* eslint-disable @stylistic/quotes */
// This file is auto-generated by generateTiers.js
// Do not edit this file directly.

// 1. Define the interface for a Quest
export interface Quest {
  id: string
  title: string
  url: string
  dependencies: string[] // Array of quest IDs
}

// 2. Export the auto-sorted quest tiers
export const questTiers: Quest[][] = [
  [
    {
      "id": "picking_up_the_pieces",
      "title": "Picking Up The Pieces",
      "url": "https://arcraiders.wiki/wiki/Picking_Up_The_Pieces",
      "dependencies": []
    },
    {
      "id": "a_first_foothold",
      "title": "A First Foothold",
      "url": "https://arcraiders.wiki/wiki/A_First_Foothold",
      "dependencies": []
    }
  ],
  [
    {
      "id": "trash_into_treasure",
      "title": "Trash Into Treasure",
      "url": "https://arcraiders.wiki/wiki/Trash_Into_Treasure",
      "dependencies": [
        "picking_up_the_pieces"
      ]
    },
    {
      "id": "clearer_skies",
      "title": "Clearer Skies",
      "url": "https://arcraiders.wiki/wiki/Clearer_Skies",
      "dependencies": [
        "picking_up_the_pieces"
      ]
    },
    {
      "id": "reduced_to_rubble",
      "title": "Reduced To Rubble",
      "url": "https://arcraiders.wiki/wiki/Reduced_To_Rubble",
      "dependencies": [
        "a_first_foothold"
      ]
    }
  ],
  [
    {
      "id": "off_the_radar",
      "title": "Off The Radar",
      "url": "https://arcraiders.wiki/wiki/Off_The_Radar",
      "dependencies": [
        "clearer_skies",
        "trash_into_treasure"
      ]
    },
    {
      "id": "with_a_trace",
      "title": "With A Trace",
      "url": "https://arcraiders.wiki/wiki/With_A_Trace",
      "dependencies": [
        "reduced_to_rubble"
      ]
    }
  ],
  [
    {
      "id": "a_bad_feeling",
      "title": "A Bad Feeling",
      "url": "https://arcraiders.wiki/wiki/A_Bad_Feeling",
      "dependencies": [
        "off_the_radar"
      ]
    }
  ],
  [
    {
      "id": "hatch_repairs",
      "title": "Hatch Repairs",
      "url": "https://arcraiders.wiki/wiki/Hatch_Repairs",
      "dependencies": [
        "a_bad_feeling"
      ]
    },
    {
      "id": "safe_passage",
      "title": "Safe Passage",
      "url": "https://arcraiders.wiki/wiki/Safe_Passage",
      "dependencies": [
        "a_bad_feeling"
      ]
    },
    {
      "id": "the_right_tool",
      "title": "The Right Tool",
      "url": "https://arcraiders.wiki/wiki/The_Right_Tool",
      "dependencies": [
        "a_bad_feeling"
      ]
    }
  ],
  [
    {
      "id": "a_better_use",
      "title": "A Better Use",
      "url": "https://arcraiders.wiki/wiki/A_Better_Use",
      "dependencies": [
        "the_right_tool"
      ]
    },
    {
      "id": "down_to_earth",
      "title": "Down To Earth",
      "url": "https://arcraiders.wiki/wiki/Down_To_Earth",
      "dependencies": [
        "hatch_repairs"
      ]
    },
    {
      "id": "what_goes_around",
      "title": "What Goes Around",
      "url": "https://arcraiders.wiki/wiki/What_Goes_Around",
      "dependencies": [
        "safe_passage"
      ]
    }
  ],
  [
    {
      "id": "greasing_her_palms",
      "title": "Greasing Her Palms",
      "url": "https://arcraiders.wiki/wiki/Greasing_Her_Palms",
      "dependencies": [
        "a_better_use"
      ]
    },
    {
      "id": "sparks_fly",
      "title": "Sparks Fly",
      "url": "https://arcraiders.wiki/wiki/Sparks_Fly",
      "dependencies": [
        "what_goes_around"
      ]
    },
    {
      "id": "the_trifecta",
      "title": "The Trifecta",
      "url": "https://arcraiders.wiki/wiki/The_Trifecta",
      "dependencies": [
        "down_to_earth"
      ]
    }
  ],
  [
    {
      "id": "doctors_orders",
      "title": "Doctor's Orders",
      "url": "https://arcraiders.wiki/wiki/Doctor%27s_Orders",
      "dependencies": [
        "greasing_her_palms"
      ]
    },
    {
      "id": "dormant_barons",
      "title": "Dormant Barons",
      "url": "https://arcraiders.wiki/wiki/Dormant_Barons",
      "dependencies": [
        "greasing_her_palms"
      ]
    }
  ],
  [
    {
      "id": "medical_merchandise",
      "title": "Medical Merchandise",
      "url": "https://arcraiders.wiki/wiki/Medical_Merchandise",
      "dependencies": [
        "doctors_orders"
      ]
    },
    {
      "id": "mixed_signals",
      "title": "Mixed Signals",
      "url": "https://arcraiders.wiki/wiki/Mixed_Signals",
      "dependencies": [
        "dormant_barons"
      ]
    },
    {
      "id": "what_we_left_behind",
      "title": "What We Left Behind",
      "url": "https://arcraiders.wiki/wiki/What_We_Left_Behind",
      "dependencies": [
        "dormant_barons"
      ]
    }
  ],
  [
    {
      "id": "a_reveal_in_ruins",
      "title": "A Reveal In Ruins",
      "url": "https://arcraiders.wiki/wiki/A_Reveal_In_Ruins",
      "dependencies": [
        "medical_merchandise"
      ]
    },
    {
      "id": "broken_monument",
      "title": "Broken Monument",
      "url": "https://arcraiders.wiki/wiki/Broken_Monument",
      "dependencies": [
        "what_we_left_behind"
      ]
    }
  ],
  [
    {
      "id": "a_lay_of_the_land",
      "title": "A Lay Of The Land",
      "url": "https://arcraiders.wiki/wiki/A_Lay_Of_The_Land",
      "dependencies": [
        "a_reveal_in_ruins"
      ]
    },
    {
      "id": "marked_for_death",
      "title": "Marked For Death",
      "url": "https://arcraiders.wiki/wiki/Marked_For_Death",
      "dependencies": [
        "broken_monument"
      ]
    },
    {
      "id": "straight_record",
      "title": "Straight Record",
      "url": "https://arcraiders.wiki/wiki/Straight_Record",
      "dependencies": [
        "broken_monument"
      ]
    }
  ],
  [
    {
      "id": "eyes_in_the_sky",
      "title": "Eyes In The Sky",
      "url": "https://arcraiders.wiki/wiki/Eyes_In_The_Sky",
      "dependencies": [
        "a_lay_of_the_land"
      ]
    },
    {
      "id": "keeping_the_memory",
      "title": "Keeping The Memory",
      "url": "https://arcraiders.wiki/wiki/Keeping_The_Memory",
      "dependencies": [
        "straight_record"
      ]
    },
    {
      "id": "market_correction",
      "title": "Market Correction",
      "url": "https://arcraiders.wiki/wiki/Market_Correction",
      "dependencies": [
        "marked_for_death"
      ]
    }
  ],
  [
    {
      "id": "a_balanced_harvest",
      "title": "A Balanced Harvest",
      "url": "https://arcraiders.wiki/wiki/A_Balanced_Harvest",
      "dependencies": [
        "eyes_in_the_sky"
      ]
    },
    {
      "id": "after_rain_comes",
      "title": "After Rain Comes",
      "url": "https://arcraiders.wiki/wiki/After_Rain_Comes",
      "dependencies": [
        "eyes_in_the_sky"
      ]
    },
    {
      "id": "echoes_of_victory_ridge",
      "title": "Echoes Of Victory Ridge",
      "url": "https://arcraiders.wiki/wiki/Echoes_Of_Victory_Ridge",
      "dependencies": [
        "keeping_the_memory"
      ]
    },
    {
      "id": "eyes_on_the_prize",
      "title": "Eyes On The Prize",
      "url": "https://arcraiders.wiki/wiki/Eyes_On_The_Prize",
      "dependencies": [
        "market_correction"
      ]
    }
  ],
  [
    {
      "id": "industrial_espionage",
      "title": "Industrial Espionage",
      "url": "https://arcraiders.wiki/wiki/Industrial_Espionage",
      "dependencies": [
        "eyes_on_the_prize"
      ]
    },
    {
      "id": "untended_garden",
      "title": "Untended Garden",
      "url": "https://arcraiders.wiki/wiki/Untended_Garden",
      "dependencies": [
        "a_balanced_harvest"
      ]
    }
  ],
  [
    {
      "id": "the_root_of_the_matter",
      "title": "The Root Of The Matter",
      "url": "https://arcraiders.wiki/wiki/The_Root_Of_The_Matter",
      "dependencies": [
        "untended_garden"
      ]
    },
    {
      "id": "unexpected_initiative",
      "title": "Unexpected Initiative",
      "url": "https://arcraiders.wiki/wiki/Unexpected_Initiative",
      "dependencies": [
        "echoes_of_victory_ridge",
        "industrial_espionage"
      ]
    }
  ],
  [
    {
      "id": "a_symbol_of_unification",
      "title": "A Symbol Of Unification",
      "url": "https://arcraiders.wiki/wiki/A_Symbol_Of_Unification",
      "dependencies": [
        "unexpected_initiative"
      ]
    },
    {
      "id": "water_troubles",
      "title": "Water Troubles",
      "url": "https://arcraiders.wiki/wiki/Water_Troubles",
      "dependencies": [
        "the_root_of_the_matter",
        "after_rain_comes"
      ]
    }
  ],
  [
    {
      "id": "celestes_journals",
      "title": "Celeste's Journals",
      "url": "https://arcraiders.wiki/wiki/Celeste%27s_Journals",
      "dependencies": [
        "a_symbol_of_unification"
      ]
    },
    {
      "id": "out_of_the_shadows",
      "title": "Out Of The Shadows",
      "url": "https://arcraiders.wiki/wiki/Out_Of_The_Shadows",
      "dependencies": [
        "a_symbol_of_unification"
      ]
    },
    {
      "id": "source_of_the_contamination",
      "title": "Source Of The Contamination",
      "url": "https://arcraiders.wiki/wiki/Source_Of_The_Contamination",
      "dependencies": [
        "water_troubles"
      ]
    },
    {
      "id": "the_majors_footlocker",
      "title": "The Major's Footlocker",
      "url": "https://arcraiders.wiki/wiki/The_Major%27s_Footlocker",
      "dependencies": [
        "a_symbol_of_unification"
      ]
    }
  ],
  [
    {
      "id": "back_on_top",
      "title": "Back On Top",
      "url": "https://arcraiders.wiki/wiki/Back_On_Top",
      "dependencies": [
        "celestes_journals"
      ]
    },
    {
      "id": "switching_the_supply",
      "title": "Switching The Supply",
      "url": "https://arcraiders.wiki/wiki/Switching_The_Supply",
      "dependencies": [
        "source_of_the_contamination"
      ]
    }
  ],
  [
    {
      "id": "a_warm_place_to_rest",
      "title": "A Warm Place To Rest",
      "url": "https://arcraiders.wiki/wiki/A_Warm_Place_To_Rest",
      "dependencies": [
        "switching_the_supply"
      ]
    },
    {
      "id": "our_presence_up_there",
      "title": "Our Presence Up There",
      "url": "https://arcraiders.wiki/wiki/Our_Presence_Up_There",
      "dependencies": [
        "back_on_top"
      ]
    }
  ],
  [
    {
      "id": "lost_in_transmission",
      "title": "Lost In Transmission",
      "url": "https://arcraiders.wiki/wiki/Lost_In_Transmission",
      "dependencies": [
        "our_presence_up_there"
      ]
    },
    {
      "id": "prescriptions_of_the_past",
      "title": "Prescriptions Of The Past",
      "url": "https://arcraiders.wiki/wiki/Prescriptions_Of_The_Past",
      "dependencies": [
        "a_warm_place_to_rest"
      ]
    }
  ],
  [
    {
      "id": "communication_hideout",
      "title": "Communication Hideout",
      "url": "https://arcraiders.wiki/wiki/Communication_Hideout",
      "dependencies": [
        "lost_in_transmission"
      ]
    },
    {
      "id": "power_out",
      "title": "Power Out",
      "url": "https://arcraiders.wiki/wiki/Power_Out",
      "dependencies": [
        "prescriptions_of_the_past"
      ]
    }
  ],
  [
    {
      "id": "flickering_threat",
      "title": "Flickering Threat",
      "url": "https://arcraiders.wiki/wiki/Flickering_Threat",
      "dependencies": [
        "power_out"
      ]
    },
    {
      "id": "into_the_fray",
      "title": "Into The Fray",
      "url": "https://arcraiders.wiki/wiki/Into_The_Fray",
      "dependencies": [
        "communication_hideout"
      ]
    }
  ],
  [
    {
      "id": "bees",
      "title": "Bees!",
      "url": "https://arcraiders.wiki/wiki/Bees!",
      "dependencies": [
        "flickering_threat"
      ]
    }
  ],
  [
    {
      "id": "espresso",
      "title": "Espresso",
      "url": "https://arcraiders.wiki/wiki/Espresso",
      "dependencies": [
        "bees"
      ]
    }
  ],
  [
    {
      "id": "life_of_a_pharmacist",
      "title": "Life Of A Pharmacist",
      "url": "https://arcraiders.wiki/wiki/Life_Of_A_Pharmacist",
      "dependencies": [
        "espresso"
      ]
    }
  ],
  [
    {
      "id": "tribute_to_toledo",
      "title": "Tribute To Toledo",
      "url": "https://arcraiders.wiki/wiki/Tribute_To_Toledo",
      "dependencies": [
        "life_of_a_pharmacist"
      ]
    }
  ],
  [
    {
      "id": "digging_up_dirt",
      "title": "Digging Up Dirt",
      "url": "https://arcraiders.wiki/wiki/Digging_Up_Dirt",
      "dependencies": [
        "tribute_to_toledo"
      ]
    }
  ],
  [
    {
      "id": "building_a_library",
      "title": "Building A Library",
      "url": "https://arcraiders.wiki/wiki/Building_A_Library",
      "dependencies": [
        "digging_up_dirt"
      ]
    },
    {
      "id": "turnabout",
      "title": "Turnabout",
      "url": "https://arcraiders.wiki/wiki/Turnabout",
      "dependencies": [
        "digging_up_dirt"
      ]
    }
  ],
  [
    {
      "id": "a_new_type_of_plant",
      "title": "A New Type Of Plant",
      "url": "https://arcraiders.wiki/wiki/A_New_Type_Of_Plant",
      "dependencies": [
        "building_a_library"
      ]
    }
  ],
  [
    {
      "id": "armored_transports",
      "title": "Armored Transports",
      "url": "https://arcraiders.wiki/wiki/Armored_Transports",
      "dependencies": [
        "a_new_type_of_plant"
      ]
    }
  ]
]
